name: ussage_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  screen_utils: ^0.0.1
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1
  firebase_storage: ^10.3.1
  shared_preferences: ^2.0.15
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/images/
  - assets/langs/
  - assets/svg/